services:
  - type: web
    name: laravel-app
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stack
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: laravel-app-db
          property: connectionString

databases:
  - name: laravel-app-db
    plan: free
